set_property IOSTANDARD LVCMOS33 [get_ports {in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN V12 [get_ports {out[2]}]
set_property PACKAGE_PIN V15 [get_ports {out[0]}]
set_property PACKAGE_PIN V14 [get_ports {out[1]}]
set_property PACKAGE_PIN V10 [get_ports {in[0]}]
set_property PACKAGE_PIN U11 [get_ports {in[1]}]
set_property PACKAGE_PIN U12 [get_ports {in[2]}]
set_property PACKAGE_PIN H6 [get_ports {in[3]}]
set_property PACKAGE_PIN V11 [get_ports {out[3]}]


set_property PACKAGE_PIN T13 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
